[config]
skip_core_tasks = true

[tasks.dev]
run_task = { name = ["dev-p", "frontend-dev"], parallel = true }

[tasks.dev-p]
run_task = { name = ["plugin-build", "copy", "start"] }

[tasks.build]
run_task = { name = ["frontend-build", "plugin-build"] }

[tasks.frontend-build]
script_runner = "@shell"
script = '''
cd frontend
pnpm build
'''

[tasks.frontend-dev]
script_runner = "@shell"
script = '''
cd frontend
pnpm dev
'''

[tasks.plugin-build]
script_runner = "@shell"
script = '''
dotnet publish ./Jellyfin.Plugin.FlowComment.sln /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary
'''

[tasks.plugin-build-release]
script_runner = "@shell"
script = '''
dotnet publish -c Release ./Jellyfin.Plugin.FlowComment.sln /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary
'''

[tasks.plugin-zip]
script_runner = "@shell"
script = '''
rm -f release.zip
zip -r release.zip ./Jellyfin.Plugin.FlowComment/bin/Release/net8.0/publish/Jellyfin.Plugin.FlowComment.dll
md5sum release.zip
'''

[tasks.release]
run_task = { name = ["frontend-build", "plugin-build-release", "plugin-zip"] }

[tasks.copy]
script_runner = "@shell"
script = '''
mkdir -p ./jellyfin/data/config/plugins/Jellyfin.Plugin.FlowComment
cp -r ./Jellyfin.Plugin.FlowComment/bin/Debug/net8.0/publish/Jellyfin.Plugin.FlowComment.* ./jellyfin/data/config/plugins/Jellyfin.Plugin.FlowComment
'''

[tasks.start]
script_runner = "@shell"
script = '''
cd jellyfin
export DUID=$(id -u)
export DGID=$(id -g)
docker-compose up --force-recreate
'''
